minor refactoring of the PIO part of builder shellscript

diff --git a/services/worker/builder b/services/worker/builder
--- a/services/worker/builder
+++ b/services/worker/builder
@@ -1012,7 +1012,9 @@ case $PLATFORM in
 
 		platformio)
 
-			THINX_FILE=$( find $BUILD_PATH/$REPO_NAME -name "thinx.h" )
+			cd $BUILD_PATH/$REPO_NAME
+
+			THINX_FILE=$( find . -name "thinx.h"  | head -n 1)
 
 			if [[ -z $THINX_FILE ]]; then
 				echo "[platformio] WARNING! No THiNX-File found! in $BUILD_PATH/$REPO_NAME: $THINX_FILE" | tee -a "${LOG_PATH}"
@@ -1077,55 +1079,41 @@ case $PLATFORM in
 
 			echo "[platformio] Docker completed <<<"
 
-			echo "Current folder contents after build:" | tee -a "${LOG_PATH}"
-			ls | tee -a "${LOG_PATH}"
-			echo "Current folder contents after build:" | tee -a "${LOG_PATH}"
-			ls $BUILD_PATH | tee -a "${LOG_PATH}"
+			echo "Current build folder contents after build:" | tee -a "${LOG_PATH}"
+			ls ./build | tee -a "${LOG_PATH}"
 
-			OUTFILE=$(find $BUILD_PATH -name "firmware.bin" -maxdepth 10 | head -n 1)
+			OUTFILE=$(find . -name "firmware.bin" -maxdepth 10 | head -n 1)
 
-			if [[ ! -f $OUTFILE ]]; then
-				echo "Output file not found, nothing build or path incorrect."
-				BUILD_SUCCESS=false
-			else
-				# Build possible, exit here on dry run...
-				if [[ ! ${RUN} ]]; then
-					echo "☢ Dry-run ${BUILD_ID} completed. Skipping actual deployment." | tee -a "${LOG_PATH}"
-					STATUS='DRY_RUN_OK'
-				else
-					echo "OUTFILE: ${OUTFILE}"
-					# Check Artifacts
-					if [[ $BUILD_SUCCESS == true ]] ; then
-						STATUS='OK'
-						# ls
+			if [[ -f $OUTFILE ]]; then
+				BUILD_SUCCESS=true
+				BIN_FILE=$( find $BUILD_PATH/$REPO_NAME -name "*.bin" | head -n 1)
+				echo "BIN_FILE: ${BIN_FILE}" | tee -a "${LOG_PATH}"
 
-						if [[ -z $(find $(pwd)/ -name "firmware.bin" -type f -size +10000c 2>/dev/null) ]]; then
-							# rm -rf $OUTFILE
-							BUILD_SUCCESS=false
-							echo "Docker build failed, build artifact size is below 10k." | tee -a "${LOG_PATH}"
-							ls
-						else
-							echo "Docker build succeeded." | tee -a "${LOG_PATH}"
-							# FIXME: Returns errors if no files found
-							echo "☢ Exporting PlatformIO artifact: ${OUTFILE}"
-							cp -vR "${OUTFILE}" "$DEPLOYMENT_PATH" | tee -a "${LOG_PATH}"
-							cp -vR "${OUTFILE}" "$TARGET_PATH" | tee -a "${LOG_PATH}"
-
-							echo "Zipping artifacts to ${BUILD_ID}.zip..." | tee -a "${LOG_PATH}"
-							zip -rq "${DEPLOYMENT_PATH}/${BUILD_ID}.zip" ${OUTFILE} ./build/*.bin ./build/*.elf # zip artefacts
-						fi
-					else
-						STATUS='FAILED'
-					fi
+				if [[ ! -f $BIN_FILE ]]; then
+					echo "BIN_FILE $BIN_FILE not found!"
+					BUILD_SUCCESS=false
+					exit 1
 				fi
-			fi
-    ;;
 
-    *)
-			MSG="If you need to support your platform, file a ticket at https://github.com/suculent/thinx-device-api/issues"
-			echo $MSG; echo $MSG | tee -a "${LOG_PATH}"
-      exit 1
-    ;;
+				# once again with size limit
+				if [[ -z $(find $BUILD_PATH/$REPO_NAME -name "*.bin" -type f -size +10000c 2>/dev/null) ]]; then
+					BUILD_SUCCESS=false
+					echo "Docker build failed, build artifact size is below 10k." | tee -a "${LOG_PATH}"
+					# ls -la | tee -a "${LOG_PATH}"
+				else
+					echo "Docker build succeeded." | tee -a "${LOG_PATH}"
+					echo "Zipping artifacts to ${BUILD_ID}.zip..." | tee -a "${LOG_PATH}"
+					zip -rq "${BUILD_PATH}/${BUILD_ID}.zip" ${BIN_FILE} ./build/**
+				fi
+			else
+				echo "[arduino] Docker build with result ${RESULT}" | tee -a "${LOG_PATH}"
+			fi
+		;;
+	*)
+		MSG="If you need to support your platform, file a ticket at https://github.com/suculent/thinx-device-api/issues"
+		echo $MSG; echo $MSG | tee -a "${LOG_PATH}"
+		exit 1
+		;;
 esac
 
 cd $DEPLOYMENT_PATH
