cleaner log; added missing infer tool; added test for missing infer tool

diff --git a/services/worker/builder b/services/worker/builder
--- a/services/worker/builder
+++ b/services/worker/builder
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if [ ! -f ./infer]; then 
+	echo "Infer tool missing!"
+	exit 1
+fi
+
 source ./infer # utility functions like parse_yaml
 
 # do not exit when subsequent tools fail...
